import { cssVarName, isThemed } from './resolve.ts';
import { springToLinear } from './spring.ts';
import type { Spring, ThemeName, Token } from './types.ts';

const REM_CATEGORIES = new Set(['font', 'space', 'size']);
const TIMESCALE = 'var(--hb-timescale, 1)';

const indent = (lines: string[], pad: string) => lines.map((l) => pad + l).join('\n');

function ms(value: number): string {
  return value === 0 ? '0ms' : `calc(${value}ms * ${TIMESCALE})`;
}

/** The CSS value of a token in its full-motion form. */
export function cssValue(token: Token, theme: ThemeName = 'light'): string {
  const { value, unit, motionType } = token;
  if (isThemed(value)) {
    return value[theme].replace(
      /\{([a-z0-9.-]+)\}/g,
      (_, ref: string) => `var(${cssVarName(ref)})`,
    );
  }
  if (motionType === 'spring') {
    const { easing, durationMs } = springToLinear(value as Spring);
    return `${ms(durationMs)} ${easing}`;
  }
  if (typeof value === 'number') {
    if (unit === 'ms') return ms(value);
    if (unit === 'px' && REM_CATEGORIES.has(token.category)) return `${value / 16}rem`;
    if (unit) return `${value}${unit}`;
    return String(value);
  }
  return String(value);
}

/** The CSS value of a motion token under reduced motion. */
function reducedCssValue(token: Token): string {
  const reduced = token.reduced?.value ?? token.value;
  if (typeof reduced === 'number' && token.unit === 'ms') return ms(reduced);
  if (typeof reduced === 'number' && token.unit) return `${reduced}${token.unit}`;
  return String(reduced);
}

const decl = (t: Token, value: string) => `${cssVarName(t.name)}: ${value};`;

export function emitCss(tokens: Token[]): string {
  const themed = tokens.filter((t) => isThemed(t.value));
  const motion = tokens.filter((t) => t.category === 'motion');
  const staticTokens = tokens.filter((t) => !isThemed(t.value) && t.category !== 'motion');
  const theme = (name: ThemeName) => themed.map((t) => decl(t, cssValue(t, name)));
  const scheme = { light: 'light', dark: 'dark', hc: 'dark' } as const;
  const themeBlock = (name: ThemeName, pad = '') =>
    indent([`color-scheme: ${scheme[name]};`, ...theme(name)], pad + '  ');
  const fullMotion = motion.map((t) => decl(t, cssValue(t)));
  const reducedMotion = motion.map((t) => decl(t, reducedCssValue(t)));

  return `/* Harbor UI tokens. Generated by packages/tokens/scripts/build.ts. Do not edit. */

/* Palette primitives are private: components use semantic variables only. */
:root {
${indent(
  staticTokens.map((t) => decl(t, cssValue(t))),
  '  ',
)}
}

/* Themes are mappings from semantic tokens to palette primitives. */
:root,
[data-theme='light'] {
${themeBlock('light')}
}

[data-theme='dark'] {
${themeBlock('dark')}
}

[data-theme='hc'] {
${themeBlock('hc')}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme]) {
${themeBlock('dark', '  ')}
  }
}

@media (prefers-contrast: more) {
  :root:not([data-theme]) {
${themeBlock('hc', '  ')}
  }
}

/*
 * Motion. Durations multiply by --hb-timescale (set it to 5 for slow motion).
 * [data-timescale] re-declares the durations so a scoped --hb-timescale takes effect there.
 */
:root,
[data-timescale] {
${indent(fullMotion, '  ')}
}

/* Reduced motion is a mapping too: movement goes to zero, fades get shorter. */
@media (prefers-reduced-motion: reduce) {
  :root,
  [data-timescale] {
${indent(reducedMotion, '    ')}
  }
}

[data-motion='reduced'],
[data-motion='reduced'] [data-timescale] {
${indent(reducedMotion, '  ')}
}
`;
}

export function emitJson(tokens: Token[], themeNames: readonly ThemeName[]): string {
  return (
    JSON.stringify(
      {
        themes: themeNames,
        tokens: tokens.map((t) => ({
          name: t.name,
          category: t.category,
          tier: t.tier,
          description: t.description,
          value: t.value,
          ...(t.unit ? { unit: t.unit } : {}),
          ...(t.motionType ? { motionType: t.motionType } : {}),
          ...(t.reduced ? { reduced: t.reduced } : {}),
          cssVar: cssVarName(t.name),
          css: isThemed(t.value)
            ? Object.fromEntries(themeNames.map((th) => [th, cssValue(t, th)]))
            : cssValue(t),
        })),
      },
      null,
      2,
    ) + '\n'
  );
}

export function emitModule(tokens: Token[], themeNames: readonly ThemeName[]) {
  const entries = Object.fromEntries(
    tokens.map((t) => [
      t.name,
      {
        category: t.category,
        tier: t.tier,
        description: t.description,
        value: t.value,
        ...(t.unit ? { unit: t.unit } : {}),
        ...(t.reduced ? { reduced: t.reduced } : {}),
        ...(t.motionType === 'spring' ? { css: springToLinear(t.value as Spring) } : {}),
        cssVar: cssVarName(t.name),
      },
    ]),
  );
  const js = `// Harbor UI tokens. Generated by packages/tokens/scripts/build.ts. Do not edit.
export const themes = ${JSON.stringify(themeNames)};
export const tokens = ${JSON.stringify(entries, null, 2)};

/** \`cssVar('color.text.muted')\` → \`'var(--hb-color-text-muted)'\` */
export function cssVar(name) {
  return \`var(--hb-\${name.replaceAll('.', '-')})\`;
}
`;
  const union = tokens.map((t) => `  | '${t.name}'`).join('\n');
  const dts = `// Harbor UI tokens. Generated by packages/tokens/scripts/build.ts. Do not edit.
export type ThemeName = ${themeNames.map((t) => `'${t}'`).join(' | ')};
export type TokenName =
${union};

export interface Spring {
  stiffness: number;
  damping: number;
  mass: number;
}

export interface TokenEntry {
  category: string;
  tier: 'primitive' | 'semantic';
  description: string;
  value: string | number | Record<ThemeName, string> | Spring;
  unit?: 'px' | 'ms' | 'em';
  reduced?: { value: string | number; strategy: 'fade' | 'none' };
  /** Springs only: the CSS linear() easing and settle duration. */
  css?: { easing: string; durationMs: number };
  cssVar: string;
}

export declare const themes: readonly ThemeName[];
export declare const tokens: Record<TokenName, TokenEntry>;
export declare function cssVar(name: TokenName): string;
`;
  return { js, dts };
}
